version: "3.6"

services:
  db_dev:
    image: postgres:14.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
